name: Docker CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node

    steps:
      - uses: actions/checkout@v1
      - name: Install & Tests
        run: |
          npm install
          npm test
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t front .
      - name: Tags
        run: |
          docker tag front ${{ secrets.DOCKER_USER }}/front:${{ github.sha }}
          docker tag front ${{ secrets.DOCKER_USER }}/front:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/front:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/front:latest
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest
    needs: cd

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "AKIAZIMZWJU7MK5TUJZM"
          aws-secret-access-key: "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"
          aws-region: "us-east-1"
      - name: Deploy to Server 1
        uses: actions/checkout@v3
        env:
          SSH_PRIVATE_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwqSVxzmxsREmvCHIreC+QeWUiQYr8WTpOGxT9dihedpNskni/J0D35l0r77DQ2Tv5RJJR304ea8Pf2sP1vn/uejJzLCuWPjfQcQoCDESks6Ee+G0wE+GfizLMBme/Crc2hQvccuXP23F88MlMJAaGZ0xzN81JVbpgle7L3IyHMWtoGLpnnaZKaA2V/AxQGqrcaE1izXXumLp2A3k2LbELYzZqYkWuAgk9nYvMkYr4Qgq1UgG9h8AQ0sB9dpliL/GgFofC07zEUhu9FHDOHW7M/k9gMz7sYP4n/kry8SGfxsI2gDPoqG6W9E11oRKxMQXGfktIItyg3YA30ebZRNvvEZHR6YuNsnoQcpn50Q+jm06JA3PWN0vOwRff1sDLq+nLqaOYts+puapd7U81D3gM0AB4+6/61TZ2RqcrkN5Wc+nSub1zkyrNdh5VGHXq1tQyQhME7i1CHurboNFdEOqK9Z+knKLG8V03P5jlwFeksw/ANK2LZ/c4xOcWYOK+a10= princy@braincuber.com"
          REMOTE_HOST: "test.braincuber.com"
          REMOTE_USER: "ec2-user"
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull
        run: |
          sudo docker pull ${{ secrets.DOCKER_USER }}/front:${{ github.sha }}
          sudo docker pull ${{ secrets.DOCKER_USER }}/front:latest
      - name: run
        run: |
          sudo docker run -d -p 80:80 ${{ secrets.DOCKER_USER }}/front:${{ github.sha }}
          sudo docker run -d -p 8080:80 ${{ secrets.DOCKER_USER }}/front:latest
